import type { Metadata } from "next";
import "@/styles/globals.css";
import Meta from "@/utils/meta/Meta";
import {
  ThemeProvider,
  ConvexClientProvider,
  ModalProvider,
} from "@/components/providers";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Atom.",
  description: "Generated by create next app",
  icons: {
    icon: [
      {
        media: "(prefers-color-scheme: light)",
        url: "/favicons/favicon.svg",
      },
      {
        media: "(prefers-color-scheme: dark)",
        url: "/favicons/favicon.svg",
      },
    ],
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <Meta title="webshark">
        <body>
          <ConvexClientProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
              storageKey="atom-theme"
            >
              <Toaster position="bottom-center" />
              <ModalProvider />
              {children}
            </ThemeProvider>
          </ConvexClientProvider>
        </body>
      </Meta>
    </html>
  );
}
